export const contextPath = '/apps/web_app_mocks/'

export const methods = [
  'GET',
  'OPTIONS',
  'POST',
  'PUT',
  'PATCH',
  'DELETE'
] as const;

export type Method = typeof methods[number];

export const statusCodes = new Map([
    [100, 'Continue'] as const,
    [101, 'Switching Protocols'] as const,
    [102, 'Processing'] as const,
    [103, 'Early Hints'] as const,
    [200, 'OK'] as const,
    [201, 'Created'] as const,
    [202, 'Accepted'] as const,
    [203, 'Non-Authoritative Information'] as const,
    [204, 'No Content'] as const,
    [205, 'Reset Content'] as const,
    [206, 'Partial Content'] as const,
    [300, 'Multiple Choices'] as const,
    [301, 'Moved Permanently'] as const,
    [302, 'Found'] as const,
    [303, 'See Other'] as const,
    [304, 'Not Modified'] as const,
    [305, 'Use Proxy'] as const,
    [306, 'Unused'] as const,
    [307, 'Temporary Redirect'] as const,
    [308, 'Permanent Redirect'] as const,
    [400, 'Bad Request'] as const,
    [401, 'Unauthorized'] as const,
    [402, 'Payment Required'] as const,
    [403, 'Forbidden'] as const,
    [404, 'Not Found'] as const,
    [405, 'Method Not Allowed'] as const,
    [406, 'Not Acceptable'] as const,
    [407, 'Proxy Authentication Required'] as const,
    [408, 'Request Timeout'] as const,
    [409, 'Conflict'] as const,
    [410, 'Gone'] as const,
    [411, 'Length Required'] as const,
    [412, 'Precondition Failed'] as const,
    [413, 'Request Entity Too Large'] as const,
    [414, 'Request-URI Too Long'] as const,
    [415, 'Unsupported Media Type'] as const,
    [416, 'Requested Range Not Satisfiable'] as const,
    [417, 'Expectation Failed'] as const,
    [418, 'I\'m a teapot'] as const,
    [421, 'Misdirected Request'] as const,
    [422, 'Unprocessable Entity'] as const,
    [423, 'Locked'] as const,
    [425, 'Too Early'] as const,
    [426, 'Upgrade Required'] as const,
    [428, 'Precondition Required'] as const,
    [429, 'Too Many Requests'] as const,
    [431, 'Request Header Fields Too Large'] as const,
    [451, 'Unavailable For Legal Reasons'] as const,
    [500, 'Internal Server Error'] as const,
    [501, 'Not Implemented'] as const,
    [502, 'Bad Gateway'] as const,
    [503, 'Service Unavailable'] as const,
    [504, 'Gateway Timeout'] as const,
    [505, 'HTTP Version Not Supported'] as const,
    [506, 'Variant Also Negotiates'] as const,
    [507, 'Insufficient Storage'] as const,
    [511, 'Network Authentication Required'] as const,
    [520, 'Web server is returning an unknown error'] as const,
    [522, 'Connection timed out'] as const,
    [524, 'A timeout occurred'] as const,
  ]
)

export type MapKey<T extends Map<any, any>> = T extends Map<infer K, any> ? K : never

export type StatusCode = MapKey<typeof statusCodes>

export const mimeToAceModeMap = new Map<string, string>([
    ['text/html', 'html'] as const,
    ['text/css', 'css'] as const,
    ['application/javascript', 'javascript'] as const,
    ['application/json', 'json'] as const,
    ['application/xml', 'xml'] as const,
    ['text/xml', 'xml'] as const,
    ['text/plain', 'text'] as const,
    ['text/markdown', 'markdown'] as const,
    ['text/x-java-source', 'java'] as const,
    ['text/x-c', 'c_cpp'] as const,
    ['text/x-c++', 'c_cpp'] as const,
    ['text/x-csharp', 'csharp'] as const,
    ['application/x-httpd-php', 'php'] as const,
    ['application/x-sh', 'sh'] as const,
    ['text/x-python', 'python'] as const,
    ['text/x-ruby', 'ruby'] as const,
    ['text/x-perl', 'perl'] as const,
    ['text/x-sql', 'sql'] as const,
    ['application/x-sql', 'sql'] as const,
    ['text/x-go', 'golang'] as const,
    ['text/x-latex', 'latex'] as const,
    ['text/x-scala', 'scala'] as const,
    ['text/x-haskell', 'haskell'] as const,
    ['text/x-typescript', 'typescript'] as const,
    ['text/x-javascript', 'javascript'] as const,
    ['application/x-json', 'json'] as const,
    ['application/x-yaml', 'yaml'] as const,
    ['text/x-yaml', 'yaml'] as const,
    ['text/x-sh', 'sh'] as const,
    ['application/x-powershell', 'powershell'] as const,
    ['application/x-lua', 'lua'] as const,
    ['application/x-php', 'php'] as const,
    ['text/x-sass', 'sass'] as const,
    ['text/x-scss', 'scss'] as const,
    ['text/x-rst', 'rst'] as const,
    ['application/x-tex', 'tex'] as const,
    ['text/x-cobol', 'cobol'] as const,
    ['application/x-java-archive', 'java'] as const,
    ['text/x-r', 'r'] as const,
    ['application/x-erlang', 'erlang'] as const,
    ['text/x-dockerfile', 'dockerfile'] as const,
    ['text/x-ini', 'ini'] as const,
    ['text/x-nginx-conf', 'nginx'] as const,
    ['application/x-jade', 'jade'] as const,
    ['application/x-ejs', 'ejs'] as const,
    ['text/x-handlebars', 'handlebars'] as const,
    ['application/x-protobuf', 'protobuf'] as const,
    ['text/x-rustsrc', 'rust'] as const,
  ]
);

export type ContentType = MapKey<typeof mimeToAceModeMap>

export const contentTypes = [
  ...mimeToAceModeMap.keys(),
  'application/vnd.rar',
  'application/zip',
  'application/x-7z-compressed',
  'application/pdf',
  'application/png',
  'image/bmp',
  'image/png',
  'image/gif',
  'image/jpeg',
  'image/webp',
  'image/svg+xml',
].sort()

export const mockTypes = [
  'STATIC',
  'STATIC_FILE',
  'JS',
  'PYTHON',
] as const;

export type MockType = typeof mockTypes[number];
